# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ab1375a758426bb3a03755128b0d2dd7fe54c266d74dd07d50d715f980c8c4d09aa1a2a2120a5cd4bf44abfc4744a94a4b2ac1fb2cf6c2b19e87c9400badab0

test:
  secret_key_base: 3e7fdbdbce68de6346a36f572f7992a424b0a3c9e02a052adf312cbdeb37c9a5bf5f7737ac53ba6e6b01533b499bfc7b0869abea8da25c781e76669cdbfbe1f2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
